#!/bin/sh -e
# removes uSHELL symlinks for utmp

if [ "$1" != "deconfigure" -a "$1" != "upgrade" ]
then
	exit 0
fi
for link in `ls /etc/alternatives/utmp-*`
do
	if readlink $link | grep -qw "/usr/bin/utmp"
	then
		update-alternatives --remove "$link" "/usr/bin/utmp"
	fi
done

